### ISSUE TITLE
Trippy flashing display on scrolling

### ISSUE THREAD

**Issue by matkoniecz** [ubipo/osmfocus#10]
If I scroll and the same colour is assigned to the same object tag description are disappearing/appearing resulting in trippy strobe effect.

It happens most of the time but not always.

**Comment by ubipo** [comment]
Thanks, I'll look into it

**Comment by ubipo** [comment]
Fixed in e181221 (v1.1.1).

**Comment by matkoniecz** [comment]
Thanks for a quick fix!
