### ISSUE TITLE
be more clear about when its loading

### ISSUE THREAD

**Issue by dpriskorn** [ubipo/osmfocus#13]
I presume you load using overpass. see the sheltermap for an example of how to inform the user clearly about loading.
https://pangose.github.io/sheltermap/?zoom=11&lat=62.4137&lon=17.3693

**Comment by ubipo** [comment]
What version are you currently using? You can check by going to `system settings > applications > OSMfocus Reborn`.

**Comment by ubipo** [comment]
More info needed
