### ISSUE TITLE
please zoom in still present on max zoom level

### ISSUE THREAD

**Issue by dpriskorn** [ubipo/osmfocus#14]
I presume thats a bug 😃

**Comment by ubipo** [comment]
What version are you currently using? You can check by going to `system settings > applications > OSMfocus Reborn`.

**Comment by pangoSE** [comment]
1.1.0 fdroid

**Comment by dpriskorn** [comment]
1.1.0-fdroid

**Comment by ubipo** [comment]
So to debug, try to:
a. Update to 1.1.1 (apk is available in releases)
b. Enable "Zoom beyond basemap max" in the app's settings (it may be that the max zoom level is too big a chunk to download, in which case I'll look into dynamically shrinking it)

**Comment by ubipo** [comment]
I improved to 'zoom in to download' behavior in v1.2.0 so this is probably fixed. In any case, I can't reproduce it (anymore).
