### ISSUE TITLE
Immediate crash on startup since 1.1.1

### ISSUE THREAD

**Issue by buergi** [ubipo/osmfocus#17]
Since upgrading to 1.1.1-fdroid I'm experiencing reproducible crashs right after start of the application. After downgrading to 1.1.0-fdroid everything is again working (although downgrade actually fails with "an unknown error", but uninstalling and reinstalling does the trick).

Device is a Huawei P20 Pro Android 10. Here is a [logcat.txt](https://github.com/ubipo/osmfocus/files/6348555/logcat.txt) dump during a crash.

**Comment by cyclingcat** [comment]
Same here (Cubot Quest, Android 9.0, v1.1.1 from F-Droid). Uninstalling and reinstalling v1.1.0 fixes it for me. I also tried it on my Samsung tablet (Android 8.1): The same behaviour.

The cycling cat

**Comment by tuukka** [comment]
Is this the same crash? To me, it happens often but not always.

![Screenshot_20210502-173428](https://user-images.githubusercontent.com/76985/116817017-28400000-ab6d-11eb-953b-ad6902501248.jpg)

**Comment by cyclingcat** [comment]
On my devices no crash log or stack trace appears. The app crashes with the standard Android app crash window:

![OSMfocus_crash](https://user-images.githubusercontent.com/32601012/116847668-49dfcc80-abeb-11eb-96f5-a8d09dd963ae.png)

(Clearing app cache and app data doesn't change anything.)

The cycling cat

**Comment by buergi** [comment]
I'm not even getting the regular Android crash popup. The app just immediately closes without any message. I got the dump I posted above via adb logcat.

**Comment by tuukka** [comment]
I was able to reproduce this crash by changing the system language to German and starting the app. Changing back to English resolved it.

The essential line from @buergi's logcat:
```
Caused by: java.util.MissingResourceException: Can't find resource for bundle org.ocpsoft.prettytime.i18n.Resources, key ePattern
```

Here's an issue about incompatibility between ProGuard and PrettyTime in some languages as well as the lines that should be added in `app/proguard-rules.pro` to solve this: https://github.com/ocpsoft/prettytime/issues/68#issuecomment-451738562
> ```
> # for prettytime
> -keep class com.ocpsoft.pretty.time.i18n.**
> -keep class org.ocpsoft.prettytime.i18n.**
> -keepnames class ** implements org.ocpsoft.prettytime.TimeUnit
> ```

**Comment by cyclingcat** [comment]
Indeed, after changing the system language to English or French the crashs are gone here as well (Android 8.1).

The cycling cat

**Comment by toas-koas** [comment]
I have the same issue with Version 1.1.1-fdroid. It crash immediately on startup

**Comment by toas-koas** [comment]
I have the same issue. Version 1.1.0 is working
