### ISSUE TITLE
RFE: add ‘follow me’ behaviour

### ISSUE THREAD

**Issue by Lee-Carre** [ubipo/osmfocus#19]
## OSMfocus Reborn version
v1.1.1-fdroid

## Feature Request
Having used the old OSMfocus, a feature I quite liked while out surveying was that by default it would start at my current GNSS position and then follow my position as I moved. This made checking the tags of various elements as convenient as walking near to them.

With OSMfocus Reborn, I have to frequently press the ‘pan to my GNSS location’ button.

Of course, manually scrolling the map should disable the ‘follow me’, with an easy way to re-enable it.

If the current behaviour is by design, then please make other possibilities user-configurable.

**Comment by ubipo** [comment]
Thanks for the RFE!

This is implemented in 00dd435 and will be released with v1.2.0. Let me know if it works like intended when you get the update.

**Comment by Lee-Carre** [comment]
The implementation isn't quite right. When follow-me is enabled, tagging of elements isn't shown (too far zoomed out). When zooming in enough to see tagging, the map doesn't follow my position any more.

**Comment by ubipo** [comment]
Oops, I kinda forgot to follow up on this. Yeah the behaviour is definitely wrong, will fix in the next release.

**Comment by ubipo** [comment]
Fixed in [v1.4.0](https://github.com/ubipo/osmfocus/releases/tag/v1.4.0).

**Comment by Lee-Carre** [comment]
Seems much better, now 🙂.

The only disparity from the original is that `follow me` isn't enabled at launch. Though, I recognise that this may be by design / invention (feature,-not-a-bug), rather than an oversight.

Thanks for implementing this; makes using Reborn much quicker, when surveying. Less disruptive to my workflow. 👍
