### ISSUE TITLE
Handle long text in tags blocking view

### ISSUE THREAD

**Issue by daniel-j-h** [ubipo/osmfocus#4]
Hey hey,

awesome to see you reviving osm focus, I was missing this for years! :heart: 

Here's what I noticed: when there is long text in tags, the boxes get quite big blocking most of the map view.

Can we handle this in a smart way? For example wrapping the line, abbreviating the text, or similar?

![Screenshot_20210313-022807](https://user-images.githubusercontent.com/527241/111014504-3ca12100-83a4-11eb-98fa-35bdd146c578.jpg)

**Comment by daniel-j-h** [comment]
Here is a second example where the boxes block each other's visibility

![Screenshot_20210313-025538](https://user-images.githubusercontent.com/527241/111035106-1ff30080-8419-11eb-827b-287ae901209f.jpg)

**Comment by ubipo** [comment]
First off: thank you so much for the donation, means a lot! :heart: 

Yeah, haven't been active for a bit but I did have two ideas to improve the situation:
- Implementing some of the filtering the original OsmFocus did (certain tags, relations)
- Making the tag-box click action open a separate details screen (currently opens osm.org)

For the second one: this ties in nicely with abbreviating stuff, both horizontally and vertically with an ellipsis.

Also like line-wrap, I'll look into that.

**Comment by ubipo** [comment]
Took a while, but I just released v1.0.1:
https://github.com/ubipo/osmfocus/releases/tag/v1.0.

For this specifically I implemented:
- Ellipsizing or wrapping, depending on a setting (defaults to ellipsizing)
- A setting to optionally hide relations
- A fix for the overlapping tagboxes.

I still want to add the click-for-more details thing and an option to hide some of the tagboxes (and for example only show the corner ones), but I'm closing this for now.

Let me know what you think!

Google Play release is in review and f-Droid needs to have a PR approved first: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8738 You can of course just download the APK from the latest release (it's the fdroid version, but eitherway it shouldn't interfere with autoupdates).

**Comment by ubipo** [comment]
Alright, PR was merged. Probably a day or so until it updates in the f-Droid app.
