### ISSUE TITLE
Check access token URL

### ISSUE THREAD

**Issue by danieldegroot2** [ubipo/osmfocus#52]
https://github.com/ubipo/osmfocus/blob/ea2ed728cd2284d0a312a1f56b37333f0dee15fc/app/src/main/java/net/pfiers/osmfocus/service/oauth/flow.kt.BAK#L39

If this URL is still in use, it may need to be updated to OAuth2, as such URLs use `/oauth2/` instead of `/oauth/`.

**Comment by ubipo** [comment]
Won't fix.
Would be part of a larger effort to add (note) editing.
