### ISSUE TITLE
Allow rotating the map

### ISSUE THREAD

**Issue by waldyrious** [ubipo/osmfocus#59]
I find it very convenient how EveryDoor allows freely rotating the map even when showing aerial imagery. It's very useful to orient the map in the same way that you are facing so as to better match what you see with what's on the map.

So, as a follow up to #5, which asked for bypassing the max zoom level of the tiles, I would like to request also that the map be freely rotatable rather than having a fixed orientation with north pointing up.

**Comment by ubipo** [comment]
Released in v1.7.0

**Comment by waldyrious** [comment]
Oh wow, that was FAST! Thanks so much for accepting the suggestion and the quick implementation! :star_struck:
