### ISSUE TITLE
Loading data is not working at all

### ISSUE THREAD

**Issue by matkoniecz** [ubipo/osmfocus#6]
At least for me OSM data is never, ever loaded.

If it is working in general - I can try debugging the app.

**Comment by ubipo** [comment]
Aha, interesting. What version are you on?
If it's not 1.0.1-fdroid or 1.0.1-gplay, can you update using the [APK in the latest release](https://github.com/ubipo/osmfocus/releases/download/v1.0.1/net.pfiers.osmfocus.apk) and try again? (1.0.1 has exception reporting, maybe that will catch something)

**Comment by matkoniecz** [comment]
![Screenshot_20210404-195549](https://user-images.githubusercontent.com/899988/113517416-18d69280-9580-11eb-9100-a0eab53fa76f.png)

Now it claim that I should zoom in even on extreme zoom in.

I can try debugging once I get back to a computer

**Comment by ubipo** [comment]
Okay, I'm first going to implement #7 (better status indicator) and #2 (faster loading). Hopefully that will make it easier to hunt down the problem.
The "Zoom in to show data" message showing when already zoomed in is already fixed, I'll let you know when I publish that version.

**Comment by matkoniecz** [comment]
Thanks, then I will wait with more thorough debugging.

**Comment by ubipo** [comment]
Alright, the status indicator has improved a lot and loading is now 44 times faster.
Do try again if you have the time, v**1.1.0**-gplay should be live on Google Play.
F-Droid is a little delayed, so if you use that you can instead install the apk from the releases page.

**Comment by matkoniecz** [comment]
It shows me cloud with arrow (downloading?) but nothing happens for loooooooooooooooooooong time.

But something is finally being loaded!

Thanks for fixing.

**Comment by ubipo** [comment]
Hmm yeah it's indeed downloading from the OSM api.
Out of curiosity: was the area densely mapped (like a city)?
If not that is a little weird.

**Comment by matkoniecz** [comment]
>  Out of curiosity: was the area densely mapped (like a city)?

Yes, very densely mapped (Kraków - https://www.openstreetmap.org/#map=19/50.07717/19.88741 ). Maybe it should default to downloading smaller area?

**Comment by ubipo** [comment]
Hmm indeed very slow. 
But difficult to fix.
