### ISSUE TITLE
Base map max zoom level not applied

### ISSUE THREAD

**Issue by waldyrious** [ubipo/osmfocus#61]
I have tried adding a custom base map ([OpenCycleMap](https://www.thunderforest.com/maps/opencyclemap/preview/)) that supposedly allows zoom levels up to 22, but when I try to actually zoom on the map, the maximum I can go to seems to be 18.

I can, of course, activate the option to zoom beyond the maximum zoom of the base map, but then the tiles get blurry. I don't think this issue is with the tiles, though, because if I disable the option to zoom beyond the base map's maximum zoom level, the app still does not allow me to go beyond 18, even though I explicitly entered "22" in the max zoom field when adding the custom base map. So it seems that somehow the app itself is refusing to allow zooming beyond 18 even when the base map is set to allow higher zoom levels.

**Comment by ubipo** [comment]
That was silly, the underlying functionality was there but indeed not applying to the map.

Fix released in [v1.7.1](https://github.com/ubipo/osmfocus/releases/tag/v1.7.1).

**Comment by waldyrious** [comment]
You're a frickin machine, dude! Thanks for another lightning fast fix! :star_struck:

**Comment by waldyrious** [comment]
Out of curiosity, when can we expect v1.7.1 to be available in Google Play Store or F-Droid?
